name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Lint, typing, security
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: pip install tox

    - name: Flake8
      run: tox -e flake8

    - name: Typing
      run: tox -e typing

    - name: Black
      run: tox -e black

    - name: Bandit
      run: tox -e bandit

  tests-ubuntu:
    name: "Test: py${{ matrix.python-version }}, Ubuntu"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: pip install tox

    - name: Run tests
      run: tox -e py

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)

  tests-other-os:
    name: "Test: py3.8, ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: pip install tox

    - name: Run tests
      run: tox -e py

  publish:
    name: "Publish package to PyPI"
    runs-on: ubuntu-18.04
    needs: [checks, tests-ubuntu, tests-other-os]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Publish to PyPI
      run: |
        pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        export TWINE_USERNAME=__token__
        export TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
        twine upload dist/*
